/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Ember, EmberInterface } from "../Ember";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "msgSender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "stoppedAt",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "nft",
        type: "address",
      },
    ],
    name: "LendingStopped",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "nftAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "lenderAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lendingId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "dailyRentPrice",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "stakedTill",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lentAt",
        type: "uint256",
      },
    ],
    name: "Lent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "renterAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "lenderAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "nft",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lendingId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rentDuration",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountPaid",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rentedAt",
        type: "uint256",
      },
    ],
    name: "Rented",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_lendingId",
        type: "uint256",
      },
    ],
    name: "getDailyRentCharges",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_lendingId",
        type: "uint256",
      },
    ],
    name: "getNFTAdapter",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_lendingId",
        type: "uint256",
      },
    ],
    name: "getNFTtokenID",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_lendingId",
        type: "uint256",
      },
    ],
    name: "getRentedTill",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_lendingId",
        type: "uint256",
      },
    ],
    name: "getStakedTill",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_nft",
        type: "address",
      },
      {
        internalType: "address",
        name: "_adapter",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxRentDuration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_perDayRentCharges",
        type: "uint256",
      },
    ],
    name: "lend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "lendingRenting",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "lenderAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "adapter",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "dailyRentPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "stakedTill",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
        ],
        internalType: "struct Demo.Lending",
        name: "lending",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address payable",
            name: "renterAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "nft",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "rentedTill",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "rentedAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "rentDuration",
            type: "uint256",
          },
        ],
        internalType: "struct Demo.Renting",
        name: "renting",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_nft",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_lendingId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_rentDuration",
        type: "uint256",
      },
    ],
    name: "rent",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_nft",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_lendingId",
        type: "uint256",
      },
    ],
    name: "stopLending",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Ember__factory {
  static readonly abi = _abi;
  static createInterface(): EmberInterface {
    return new utils.Interface(_abi) as EmberInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Ember {
    return new Contract(address, _abi, signerOrProvider) as Ember;
  }
}
